### ISSUE TITLE
Crashes after launch (appimage)

### ISSUE THREAD

**Issue by Bright-9** [kotatogram/kotatogram-desktop#223]
### Steps to reproduce

1. Open ./Kotatogram
2. Program crash

### Expected behaviour

Open ./Kotatogram and it keeps working

### Actual behaviour

If I'm connected to internet, the program crashes.  
But if I disconnect, it keeps open.

I've tried to clean the cache and all the media downloaded with the internet off, in the settings page, but it didn't solve the problem.

It seems like there's an message or media corrupted inside an chat that the program can't read, and when I connect, it access this message and crashes.. But I can't confirm.

### Operating system

Debian 10 Buster - KDE Plasma

### Version of Kotatogram Desktop

1.4.1

### Installation source

Static binary from official website

**Comment by ilya-fedin** [comment]
1. extract the appimage with `./Kotatogram --appimage-extract`
2. launch it with gdb: `gdb ./squashfs-root/usr/bin/kotatogram-desktop`, then `run` in gdb command prompt
3. make it crash
4. `bt full`

**Comment by Bright-9** [comment]
When I send ` run` in gdb, the window opens but it didn't load any of my chats. Also, it seems to be 'frozen', because I can't go to the settings or any button in hamburguer menu on the top left.

Anyway, this is the exit: 

```
(gdb) run
Starting program: /home/USER/Appimages/Kotatogram/squashfs-root/usr/bin/kotatogram-desktop 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

(kotatogram-desktop:2935): Kotatogram-WARNING **: 11:05:05.692: GTK integration is disabled, some features unavailable.
[New Thread 0x7fffecc3c700 (LWP 2939)]
[New Thread 0x7fffe7fff700 (LWP 2940)]
[New Thread 0x7fffe560a700 (LWP 2943)]
[New Thread 0x7fffdffff700 (LWP 2944)]
[New Thread 0x7fffdf7fe700 (LWP 2945)]
[New Thread 0x7fffdeffd700 (LWP 2946)]
[New Thread 0x7fffdd25e700 (LWP 2947)]
[New Thread 0x7fffdc9ba700 (LWP 2948)]
[New Thread 0x7fffc3fff700 (LWP 2949)]
[New Thread 0x7fffc1126700 (LWP 2950)]
[ALSOFT] (EE) Failed to set real-time priority for thread: Operação não permitida (1)
[New Thread 0x7fffc0925700 (LWP 2951)]
[New Thread 0x7fffbbfff700 (LWP 2952)]
[New Thread 0x7fffbb7fe700 (LWP 2953)]
[New Thread 0x7fffb9131700 (LWP 2954)]
[New Thread 0x7fffb8930700 (LWP 2955)]
[New Thread 0x7fff9fbb0700 (LWP 2956)]
error: : cannot open
error: : cannot open
error: : cannot open
[New Thread 0x7fff9ebae700 (LWP 2957)]
[New Thread 0x7fff9f3af700 (LWP 2958)]
[New Thread 0x7fff9e3ad700 (LWP 2959)]
[New Thread 0x7fff9dbac700 (LWP 2960)]
[New Thread 0x7fff9d3ab700 (LWP 2961)]
[New Thread 0x7fff87fff700 (LWP 2962)]
[Thread 0x7fff9f3af700 (LWP 2958) exited]
[Thread 0x7fff9ebae700 (LWP 2957) exited]
[Thread 0x7fff9dbac700 (LWP 2960) exited]
[Thread 0x7fff9d3ab700 (LWP 2961) exited]
[Thread 0x7fff87fff700 (LWP 2962) exited]
[New Thread 0x7fff87fff700 (LWP 2963)]
[New Thread 0x7fff9d3ab700 (LWP 2964)]
[New Thread 0x7fff9dbac700 (LWP 2965)]
[New Thread 0x7fff9f3af700 (LWP 2966)]
[New Thread 0x7fff9ebae700 (LWP 2967)]
[New Thread 0x7fff85ec3700 (LWP 2968)]
[Thread 0x7fff9dbac700 (LWP 2965) exited]
[Thread 0x7fff9f3af700 (LWP 2966) exited]
[Thread 0x7fff9ebae700 (LWP 2967) exited]
[Thread 0x7fff85ec3700 (LWP 2968) exited]
[New Thread 0x7fff85ec3700 (LWP 2969)]
[New Thread 0x7fff9ebae700 (LWP 2970)]
[Thread 0x7fff85ec3700 (LWP 2969) exited]
[Thread 0x7fff9ebae700 (LWP 2970) exited]

Thread 1 "kotatogram-desk" received signal SIGABRT, Aborted.
0x00007ffff15b07bb in raise () from /lib/x86_64-linux-gnu/libc.so.6
(gdb) bt full
#0  0x00007ffff15b07bb in raise () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#1  0x00007ffff159b535 in abort () from /lib/x86_64-linux-gnu/libc.so.6
No symbol table info available.
#2  0x00000000007e9bac in base::assertion::fail(char const*, char const*, int) ()
No symbol table info available.
#3  0x00000000020c0b1c in base::Timer::setTimeout(long) ()
No symbol table info available.
#4  0x00000000020c0b5f in base::Timer::start(long, Qt::TimerType, base::Timer::Repeat) ()
No symbol table info available.
#5  0x0000000001493cde in Data::Session::registerMessageTTL(int, gsl::not_null<HistoryItem*>) ()
No symbol table info available.
#6  0x00000000017b253d in HistoryItem::applyTTL(int) ()
No symbol table info available.
#7  0x00000000017e5996 in HistoryMessage::HistoryMessage(gsl::not_null<History*>, MTPDmessage const&, base::flags<MTPDmessage_ClientFlag>) ()
No symbol table info available.
#8  0x00000000017b4570 in HistoryItem::Create(gsl::not_null<History*>, tl::boxed<MTPmessage> const&, base::flags<MTPDmessage_ClientFlag>) ()
No symbol table info available.
#9  0x0000000001799606 in History::createItem(tl::boxed<MTPmessage> const&, base::flags<MTPDmessage_ClientFlag>, bool) ()
No symbol table info available.
#10 0x00000000017a4581 in History::addNewMessage(tl::boxed<MTPmessage> const&, base::flags<MTPDmessage_ClientFlag>, NewMessageType) ()
No symbol table info available.
#11 0x0000000001487f5a in Data::Session::addNewMessage(tl::boxed<MTPmessage> const&, base::flags<MTPDmessage_ClientFlag>, NewMessageType) ()
No symbol table info available.
#12 0x00000000014981d0 in Data::Session::processMessages(QVector<tl::boxed<MTPmessage> > const&, NewMessageType) ()
No symbol table info available.
#13 0x000000000149e435 in Data::Session::applyDialogs(Data::Folder*, QVector<tl::boxed<MTPmessage> > const&, QVector<tl::boxed<MTPdialog> > const&, std::optional<int>) ()
No symbol table info available.
#14 0x0000000001fb536b in std::_Function_handler<void (tl::boxed<MTPmessages_dialogs> const&), ApiWrap::requestMoreDialogs(Data::Folder*)::{lambda(tl::boxed<MTPmessages_dialogs> const&)#1}>::_M_invoke(std::_Any_data const&, tl::boxed<MTPmessages_dialogs> const&) ()
No symbol table info available.
#15 0x0000000001fcbdca in std::_Function_handler<bool (MTP::Response const&), base::details::moveable_callable_wrap<MTP::Sender::RequestBuilder::MakeDoneHandler<tl::boxed<MTPmessages_dialogs>, base::unique_function<void (tl::boxed<MTPmessages_dialogs> const&)> >(gsl::not_null<MTP::Sender*>, base::unique_function<void (tl::boxed<MTPmessages_dialogs> const&)>&&)::{lambda(MTP::Response const&)#1}> >::_M_invoke(std::_Any_data const&, MTP::Response const&) ()
No symbol table info available.
#16 0x0000000001b48d5f in MTP::Instance::Private::processCallback(MTP::Response const&) ()
No symbol table info available.
#17 0x0000000001b53fbd in MTP::details::Session::tryToReceive() ()
No symbol table info available.
#18 0x00000000013533ca in Core::Sandbox::notifyOrInvoke(QObject*, QEvent*) ()
No symbol table info available.
#19 0x00000000013534c6 in Core::Sandbox::notify(QObject*, QEvent*) ()
No symbol table info available.
#20 0x00007ffff2484a0a in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /home/USER/Appimages/Kotatogram/squashfs-root/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#21 0x00007ffff2487281 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /home/USER/Appimages/Kotatogram/squashfs-root/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#22 0x00007ffff24dddc3 in ?? () from /home/USER/Appimages/Kotatogram/squashfs-root/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#23 0x00007ffff4590fee in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#24 0x00007ffff4591288 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#25 0x00007ffff459131c in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
No symbol table info available.
#26 0x00007ffff24dd42e in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /home/USER/Appimages/Kotatogram/squashfs-root/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#27 0x00007ffff24835fb in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /home/USER/Appimages/Kotatogram/squashfs-root/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#28 0x00007ffff248b510 in QCoreApplication::exec() () from /home/USER/Appimages/Kotatogram/squashfs-root/usr/bin/../lib/libQt5Core.so.5
No symbol table info available.
#29 0x000000000135227f in Core::Sandbox::start() ()
--Type <RET> for more, q to quit, c to continue without paging--
```

**Comment by ilya-fedin** [comment]
It's a crash due to int overflow in messages auto-deletion :(. Unfortunately, all you can do is to wait for a new release on new tdesktop sources (i don't know when that will happen).

**Comment by Bright-9** [comment]
Okay, thanks!

**Comment by Bright-9** [comment]
Okay, thanks! I'll be using in the browser meanwhile

**Comment by RadRussianRus** [comment]
You can temporarily use beta, which backports 1 month auto-delete option, thus fixing this issue.
