### ISSUE TITLE
Building error: ImportError: No module named run_cmake

### ISSUE THREAD

**Issue by OnkelTem** [kotatogram/kotatogram-desktop#353]
### Steps to reproduce

While following the instructions from here: https://github.com/kotatogram/kotatogram-desktop/blob/dev/docs/building-linux.md

1. clone the repo and cd to `kotatogram-desktop`
2. run `docker build -t kotatogram-desktop:centos_env Telegram/build/docker/centos_env/` to prepare libraries
3. run build command:
```
$ docker run --rm -it \
    -v $PWD:/usr/src/tdesktop \
    kotatogram-desktop:centos_env \
    /usr/src/tdesktop/Telegram/build/docker/centos_env/build.sh \
    -D TDESKTOP_API_ID=YOUR_API_ID \
    -D TDESKTOP_API_HASH=YOUR_API_HASH \
    -D DESKTOP_APP_USE_PACKAGED=OFF \
    -D DESKTOP_APP_DISABLE_CRASH_REPORTS=ON
```
and see it fails: 
```
Traceback (most recent call last):
  File "/usr/src/tdesktop/Telegram/configure.py", line 13, in <module>
    import run_cmake
ImportError: No module named run_cmake
Error: /usr/src/tdesktop/out is not a directory
```

### Expected behaviour

Building works

### Actual behaviour

Building is failing

### Operating system

Linux Kubuntu 20.04

### Version of Kotatogram Desktop

dev

### Installation source

Other (unofficial) source

### Logs

```shell
Traceback (most recent call last):
  File "/usr/src/tdesktop/Telegram/configure.py", line 13, in <module>
    import run_cmake
ImportError: No module named run_cmake
Error: /usr/src/tdesktop/out is not a directory
```

**Comment by OnkelTem** [comment]
The problem was that I didn't use `--recursive` while cloning the repo 🤦🏼 

Sorry.
